apiVersion: loom/v1
kind: Tool
metadata:
  name: calculator
  description: Perform basic mathematical calculations
  version: "1.0"
  labels:
    category: math
    maturity: stable

spec:
  input_schema:
    type: object
    properties:
      expression:
        type: string
        description: Mathematical expression to evaluate (e.g., "2 + 2", "sqrt(16)", "sin(pi/2)")

    required:
      - expression

  output_schema:
    type: object
    properties:
      result:
        type: number
        description: The calculated result
      formatted:
        type: string
        description: Human-readable result with units
    required:
      - result

  implementation:
    type: builtin
    handler: math_evaluator
    config:
      allowed_functions:
        - add
        - subtract
        - multiply
        - divide
        - sqrt
        - pow
        - sin
        - cos
        - tan
        - log
        - exp
      max_precision: 10
      safe_mode: true  # Prevent dangerous operations

  examples:
    - description: Simple addition
      input:
        expression: "2 + 2"
      output:
        result: 4
        formatted: "4"

    - description: Square root
      input:
        expression: "sqrt(16)"
      output:
        result: 4
        formatted: "4"

    - description: Complex expression
      input:
        expression: "(10 + 5) * 2 / 3"
      output:
        result: 10
        formatted: "10"
