apiVersion: loom/v1
kind: Tool
metadata:
  name: execute_code
  description: Execute code in a secure sandboxed environment
  version: "1.0"
  labels:
    category: development
    risk: high
    maturity: beta

spec:
  input_schema:
    type: object
    properties:
      code:
        type: string
        description: Code to execute

      language:
        type: string
        description: Programming language
        enum: ["python", "javascript", "bash", "go"]

      stdin:
        type: string
        description: Standard input for the program
        default: ""

      timeout_seconds:
        type: integer
        description: Execution timeout
        default: 30
        minimum: 1
        maximum: 300

      environment:
        type: object
        description: Environment variables
        additionalProperties:
          type: string

    required:
      - code
      - language

  output_schema:
    type: object
    properties:
      stdout:
        type: string
        description: Standard output
      stderr:
        type: string
        description: Standard error
      exit_code:
        type: integer
        description: Exit code (0 = success)
      execution_time_ms:
        type: number
        description: Execution time in milliseconds
      timed_out:
        type: boolean
        description: Whether execution exceeded timeout

  implementation:
    type: docker
    config:
      # Sandbox configuration
      sandbox:
        image_map:
          python: "python:3.11-slim"
          javascript: "node:20-slim"
          bash: "bash:5.2"
          go: "golang:1.22-alpine"

        # Security constraints
        network: none  # No network access
        memory_limit: "512MB"
        cpu_limit: "1.0"
        pids_limit: 100
        readonly_rootfs: true
        no_new_privileges: true

        # Filesystem
        working_dir: "/workspace"
        temp_dir: "/tmp"
        max_file_size: "10MB"

        # Blocked syscalls
        seccomp_profile: "runtime/default"
        capabilities_drop:
          - ALL

      # Resource limits
      resources:
        max_execution_time_seconds: 300
        max_output_size_bytes: 1048576  # 1MB
        max_memory_bytes: 536870912  # 512MB

  examples:
    - description: Simple Python script
      input:
        code: |
          print("Hello, World!")
          print(2 + 2)
        language: "python"
      output:
        stdout: "Hello, World!\n4\n"
        stderr: ""
        exit_code: 0
        execution_time_ms: 45.2
        timed_out: false

    - description: JavaScript calculation
      input:
        code: |
          const result = [1, 2, 3, 4, 5].reduce((sum, n) => sum + n, 0);
          console.log(result);
        language: "javascript"
      output:
        stdout: "15\n"
        stderr: ""
        exit_code: 0

  safety:
    requires_approval: true
    approval_timeout_seconds: 60

    # Pattern-based blocking
    blocked_patterns:
      - "import os"
      - "import subprocess"
      - "eval("
      - "exec("
      - "__import__"
      - "open("

    # Allowed imports (whitelist)
    allowed_imports:
      python:
        - math
        - json
        - datetime
        - re
        - collections
      javascript:
        - lodash
        - moment

  metadata:
    documentation: "https://docs.loom.dev/tools/code-executor"
    security_level: high
    audit_logging: required
    use_cases:
      - "Data transformation scripts"
      - "Quick calculations"
      - "Algorithm testing"
      - "Code snippet validation"
