# Generic Public API Backend Configuration
# Usage: Reference this file in your looms.yaml agent configuration
#
# This backend works with any public REST API that doesn't require authentication.
# Set the API_BASE_URL environment variable to point to your API endpoint.
#
# Examples:
#   export API_BASE_URL=https://api.open-meteo.com/v1
#   export API_BASE_URL=https://api.github.com
#   export API_BASE_URL=https://jsonplaceholder.typicode.com

apiVersion: loom/v1
kind: Backend
name: public-api-backend
type: rest
description: Generic REST API backend for public endpoints (no authentication)

# REST API connection settings
rest:
  # Base URL can be overridden via environment variable
  base_url: ${API_BASE_URL:-https://api.example.com}

  # Default headers for common JSON APIs
  headers:
    Accept: application/json
    Content-Type: application/json
    User-Agent: loom-agent/1.0

  # Timeouts and retries
  timeout_seconds: 30
  max_retries: 3
  retry_delay_seconds: 1

# Capabilities configuration
capabilities:
  query_execution: false
  schema_discovery: false
  metadata: true
  resource_listing: true
  custom_operations: true

# Optional: Health check configuration
# Uncomment and configure if your API supports health checks
# health_check:
#   enabled: true
#   endpoint: /health
#   interval_seconds: 300
#   timeout_seconds: 10
