# GraphQL Backend Configuration
# Usage: Reference this file in your looms.yaml agent configuration

apiVersion: loom/v1
kind: Backend
name: graphql-backend
type: graphql
description: GraphQL API backend with authentication

graphql:
  # GraphQL endpoint
  endpoint: ${GRAPHQL_ENDPOINT:-https://api.example.com/graphql}

  # Authentication
  auth:
    type: bearer
    token: ${GRAPHQL_TOKEN}
    header_name: Authorization

  # Custom headers
  headers:
    Content-Type: application/json
    Accept: application/json

  # Timeout
  timeout_seconds: 30

# Schema discovery
schema_discovery:
  enabled: true
  cache_ttl_seconds: 3600

# Tool generation (GraphQL operations)
tool_generation:
  enable_all: false
  tools:
    - query
    - mutation

# Health check
health_check:
  enabled: true
  interval_seconds: 300
  timeout_seconds: 10

# Example endpoints:
# - GitHub GraphQL: https://api.github.com/graphql
# - Shopify GraphQL: https://{shop}.myshopify.com/admin/api/{version}/graphql.json
# - Hasura: https://{project}.hasura.app/v1/graphql
