# Example backend configuration for streamable-http MCP server
# This demonstrates the modern MCP transport (2025-03-26 spec) with
# session management and stream resumption support.
#
# ✅ RECOMMENDED: This is the modern MCP transport
# For legacy servers, see mcp-http.yaml
#
# Usage: Reference this file in your looms.yaml agent configuration

apiVersion: loom/v1
kind: Backend
name: mcp-streamable-http-backend
type: mcp
description: MCP backend using streamable-http transport (modern)

# MCP configuration for streamable-http transport
mcp:
  # Transport type: streamable-http (modern MCP spec)
  # Other options: "stdio", "http" (legacy), "sse" (legacy)
  transport: streamable-http

  # URL endpoint for the MCP server (single unified endpoint)
  url: https://api.example.com/mcp

  # Enable this server (default: false for safety)
  # Set to true to activate this MCP server
  enabled: true

  # Enable session management (recommended for streamable-http)
  # Server returns Mcp-Session-Id header during initialization
  # Client includes it in subsequent requests
  enable_sessions: true

  # Enable stream resumption (optional, provides fault tolerance)
  # Server assigns event IDs to SSE events
  # Client can resume from last received event after disconnect
  enable_resumption: true

# MCP backends automatically support these capabilities
capabilities:
  query_execution: false
  schema_discovery: false
  metadata: true
  resource_listing: true
  custom_operations: true

# Notes:
# - Streamable-HTTP is the recommended transport for remote MCP servers
# - Single unified endpoint handles both POST (send) and GET (listen) methods
# - Session management provides stateful connections with automatic recovery
# - Stream resumption prevents message loss on temporary disconnects
# - For local MCP servers, consider using stdio transport instead
# - For legacy servers, use "http" or "sse" transport (deprecated)

# Example with custom headers (for authentication):
# headers:
#   Authorization: "Bearer ${API_TOKEN}"
#   X-Custom-Header: "value"
