// Copyright 2026 Teradata
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package index implements a hierarchical PageIndex-style router tree over
// the skill library. The tree is built offline (or in a goroutine on first
// boot) by Builder, persisted by Store, walked by Router during discovery,
// and cached per-session by Cache.
//
// See docs/architecture/skills-overhaul.md for the design.
package index

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/teradata-labs/loom/pkg/skills"
)

// Root is the path of the synthetic root node. Every built index has a node
// with ID derived from this path.
const Root = ""

// UnclassifiedRoot is where skills with no parent_index_path are placed.
// Skills are grouped by their Domain under this root so legacy skills still
// surface to the router with sensible structure.
const UnclassifiedRoot = "unclassified"

// NodeID returns the stable hash-derived id for a tree path. Empty path
// returns the root id. Callers should never construct ids by hand; this
// keeps id generation centralized.
func NodeID(path string) string {
	h := sha256.Sum256([]byte("skill-index/" + path))
	return hex.EncodeToString(h[:16])
}

// SplitPath returns the segments of a slash-delimited path with surrounding
// slashes trimmed. SplitPath("") returns nil; SplitPath("a/b/c") returns
// []string{"a", "b", "c"}.
func SplitPath(path string) []string {
	path = strings.Trim(path, "/")
	if path == "" {
		return nil
	}
	return strings.Split(path, "/")
}

// JoinPath joins segments with "/". Empty segments are dropped.
func JoinPath(segments ...string) string {
	out := make([]string, 0, len(segments))
	for _, s := range segments {
		s = strings.Trim(s, "/")
		if s == "" {
			continue
		}
		out = append(out, s)
	}
	return strings.Join(out, "/")
}

// Parent returns the path of the parent node. Parent("a/b/c") -> "a/b".
// Parent of the root or a single-segment path returns Root.
func Parent(path string) string {
	segments := SplitPath(path)
	if len(segments) <= 1 {
		return Root
	}
	return JoinPath(segments[:len(segments)-1]...)
}

// SkillPath computes the index path a skill belongs under. Skills with an
// explicit ParentIndexPath use it directly; others are placed under
// "unclassified/<domain>" (with a fallback to "unclassified/general"
// when domain is empty).
func SkillPath(s *skills.Skill) string {
	if s == nil {
		return Root
	}
	if s.ParentIndexPath != "" {
		return strings.Trim(s.ParentIndexPath, "/")
	}
	domain := strings.TrimSpace(s.Domain)
	if domain == "" {
		domain = "general"
	}
	return JoinPath(UnclassifiedRoot, domain)
}

// AncestorPaths returns every prefix path of the given path, root first.
// For "a/b/c": [Root, "a", "a/b", "a/b/c"]. Useful when constructing
// parent nodes during index build.
func AncestorPaths(path string) []string {
	segments := SplitPath(path)
	out := []string{Root}
	for i := 1; i <= len(segments); i++ {
		out = append(out, JoinPath(segments[:i]...))
	}
	return out
}

// ContentHash hashes the salient fields of a Skill that drive the router
// summary. When this hash drifts, the node containing the skill is dirtied
// and its summary is regenerated by Builder. Order-independent across
// skills attached to the same node.
func ContentHash(skills []*skills.Skill) string {
	if len(skills) == 0 {
		return ""
	}
	type rec struct {
		Name        string
		Title       string
		Description string
		Domain      string
		Path        string
	}
	recs := make([]rec, 0, len(skills))
	for _, s := range skills {
		recs = append(recs, rec{
			Name:        s.Name,
			Title:       s.Title,
			Description: s.Description,
			Domain:      s.Domain,
			Path:        SkillPath(s),
		})
	}
	sort.Slice(recs, func(i, j int) bool { return recs[i].Name < recs[j].Name })
	h := sha256.New()
	for _, r := range recs {
		fmt.Fprintf(h, "%s\x00%s\x00%s\x00%s\x00%s\n",
			r.Name, r.Title, r.Description, r.Domain, r.Path)
	}
	return hex.EncodeToString(h.Sum(nil))
}

// Tree is a navigation-friendly view of a SkillIndex: child lookup by id
// and parent->children adjacency. Built once from a SkillIndex; safe to
// share read-only across goroutines.
type Tree struct {
	Index    *skills.SkillIndex
	byID     map[string]*skills.SkillIndexNode
	children map[string][]*skills.SkillIndexNode
}

// NewTree wraps a SkillIndex with id and adjacency lookup tables.
func NewTree(idx *skills.SkillIndex) *Tree {
	t := &Tree{
		Index:    idx,
		byID:     make(map[string]*skills.SkillIndexNode, len(idx.Nodes)),
		children: make(map[string][]*skills.SkillIndexNode),
	}
	for _, n := range idx.Nodes {
		t.byID[n.ID] = n
	}
	for _, n := range idx.Nodes {
		for _, childID := range n.Children {
			if c, ok := t.byID[childID]; ok {
				t.children[n.ID] = append(t.children[n.ID], c)
			}
		}
	}
	return t
}

// Get returns the node for the given id, or nil if not present.
func (t *Tree) Get(id string) *skills.SkillIndexNode {
	if t == nil {
		return nil
	}
	return t.byID[id]
}

// Root returns the root node (synthetic, depth=0). Returns nil when the
// index is empty.
func (t *Tree) RootNode() *skills.SkillIndexNode {
	if t == nil {
		return nil
	}
	return t.byID[t.Index.RootID]
}

// Children returns the resolved child nodes of the given parent id, or nil
// when the parent has no children. The returned slice is read-only.
func (t *Tree) Children(parentID string) []*skills.SkillIndexNode {
	if t == nil {
		return nil
	}
	return t.children[parentID]
}
