# Documentation Generation Workflow
# Uses parallel pattern to generate different types of documentation independently

apiVersion: loom/v1
kind: Workflow
metadata:
  name: comprehensive-documentation
  description: Generate API docs, user guide, and examples in parallel
  labels:
    category: documentation
    complexity: medium

spec:
  type: parallel  # Changed from pattern: parallel
  merge_strategy: concatenate
  timeout_seconds: 600

  tasks:
    - agent_id: api-documenter
      prompt: "Create API documentation for the workflow orchestration system. Include endpoint descriptions, request/response formats, and authentication requirements."
    - agent_id: technical-writer
      prompt: "Write a user-friendly guide for the workflow orchestration system. Include getting started instructions, common use cases, and troubleshooting tips."
    - agent_id: example-creator
      prompt: "Create practical code examples for the workflow orchestration system. Include sample YAML files for each pattern type (debate, fork-join, pipeline, parallel, conditional)."

# Agent configs used (from $LOOM_DATA_DIR/agents/):
# - api-documenter.yaml: API documentation specialist for creating comprehensive technical documentation
# - technical-writer.yaml: Technical writer for user-friendly guides and tutorials
# - example-creator.yaml: Example code specialist for practical, real-world code samples

# Note: Each task in the parallel pattern has its own specific prompt. The tasks execute
# independently and their results are concatenated using the merge_strategy.
