# Feature Implementation Pipeline
# Uses pipeline pattern for sequential feature development: design → implement → test

apiVersion: loom/v1
kind: Workflow
metadata:
  name: feature-implementation-pipeline
  description: Sequential workflow for implementing a new feature
  labels:
    category: development
    complexity: high

spec:
  type: pipeline  # Changed from pattern: pipeline
  initial_prompt: "Design a user authentication system with the following requirements: Support email/password and OAuth2 (Google, GitHub), JWT-based session management, Role-based access control (RBAC), Account lockout after failed attempts, Password reset functionality"

  stages:
    - agent_id: api-architect
      prompt_template: |
        Based on the requirements: {{previous}}

        Design the API specification including:
        - REST endpoints with HTTP methods
        - Request/response schemas
        - Authentication flow
        - Error handling strategy

    - agent_id: backend-developer
      prompt_template: |
        Based on this API specification: {{previous}}

        Implement the backend code including:
        - Database schema (SQL DDL)
        - API endpoint implementations
        - Authentication middleware
        - Input validation
        - Error handling

    - agent_id: test-engineer
      prompt_template: |
        Based on this implementation: {{previous}}

        Create comprehensive tests:
        - Unit tests for each component
        - Integration tests for API endpoints
        - Security tests (injection attacks, auth bypass)
        - Performance tests for critical operations
        - Test data setup and teardown

  pass_full_history: false

# Example execution:
# looms workflow run feature-pipeline.yaml
#
# Agent configs used (from $LOOM_DATA_DIR/agents/):
# - api-architect.yaml: API architect specializing in RESTful API design
# - backend-developer.yaml: Senior backend developer implementing production systems
# - test-engineer.yaml: Test engineer creating comprehensive testing strategies
