# Technology Selection Swarm Workflow
# Uses swarm pattern for collective decision-making through voting

apiVersion: loom/v1
kind: Workflow
metadata:
  name: technology-swarm
  description: Collective voting for technology selection decisions
  labels:
    category: decision-making
    complexity: low

spec:
  type: swarm  # Changed from pattern: swarm
  strategy: majority
  confidence_threshold: 0.7
  share_votes: false

  agent_ids:
    - database-expert
    - performance-engineer
    - devops-specialist
    - cost-analyst
    - senior-architect

# Agent configs used (from $LOOM_DATA_DIR/agents/):
# - database-expert.yaml: Database technology expert for evaluating database options
# - performance-engineer.yaml: Performance engineering specialist for throughput and latency analysis
# - devops-specialist.yaml: DevOps specialist for operational excellence assessment
# - cost-analyst.yaml: Technology cost analyst for TCO evaluation
# - senior-architect.yaml: Senior architect judge for synthesizing swarm voting results

# Example usage:
# "Which database technology should we use for our analytics platform that needs to handle
# time-series data with high write throughput and complex analytical queries?
#
# Options to consider:
# A) PostgreSQL with TimescaleDB extension
# B) ClickHouse
# C) Apache Druid
# D) InfluxDB
#
# Evaluate based on:
# - Write performance (1M+ events/second)
# - Query performance for complex aggregations
# - Operational complexity
# - Cost and licensing
# - Team expertise requirements"
