apiVersion: loom/v1
kind: Workflow
metadata:
  name: customer-health-workflow
  version: "3.0.0"
  description: "Multi-agent workflow for customer health analysis, quality validation, alerting, and presentation"
  labels:
    domain: customer-analytics
    category: analysis
    backend: teradata

spec:
  entrypoint: health-coordinator

  agents:
    - name: health-coordinator
      agent: health-coordinator
      description: "User-facing coordinator that manages the customer health analysis process (event-driven)"

    - name: data-analyst
      agent: data-analyst
      description: "Executes Teradata SQL queries and provides data analysis"

    - name: quality-checker
      agent: quality-checker
      description: "Validates health score quality and identifies data issues"

    - name: alert-generator
      agent: alert-generator
      description: "Detects health score changes and generates CSM alerts"

    - name: presentation-agent
      agent: presentation-agent
      description: "Creates executive dashboards, reports, and visualizations"

  # Communication pattern documentation (advisory only - not enforced by runtime)
  #
  # The "hub-and-spoke" pattern emerges naturally through Loom's tri-modal communication:
  # - Message Queue: send_message/receive_message for direct agent-to-agent communication
  # - Broadcast Bus: publish/subscribe for topic-based messaging (not used in this workflow)
  # - Shared Memory: shared_memory_write/read for shared state (not used in this workflow)
  #
  # The coordinator acts as a hub because:
  # 1. It's the entrypoint (users interact with it first)
  # 2. Its system prompt instructs it to coordinate with specialist agents
  # 3. Specialist agents' prompts instruct them to respond to the coordinator
  # 4. Coordinator is EVENT-DRIVEN - responses automatically injected (no polling)
  #
  # This field documents the intended communication topology but is not parsed
  # or enforced by the runtime - the pattern emerges from agent configuration.
  communication:
    pattern: "hub-and-spoke"
    hub: health-coordinator

  config:
    timeout_seconds: 1800  # 30 minutes for complete analysis
    max_workflow_turns: 200

  observability:
    export_traces: true
    export_metrics: true
    tags:
      workflow: customer-health
      version: "3.0.0"
      domain: customer-analytics
