# Architecture Debate Workflow
# Uses debate pattern to make architectural decisions through structured discussion

apiVersion: loom/v1
kind: Workflow
metadata:
  name: architecture-debate
  description: Structured debate for making architecture decisions
  labels:
    category: design
    complexity: medium

spec:
  type: debate  # Changed from pattern: debate
  rounds: 3

  agent_ids:
    - architect-advocate
    - pragmatist-engineer
    - senior-architect

# Agent configs used (from ~/.loom/agents/):
# - architect-advocate.yaml: Advocate for architectural best practices and long-term maintainability
# - pragmatist-engineer.yaml: Pragmatist engineer for practical solutions and business constraints
# - senior-architect.yaml: Senior architect moderator for synthesizing debate outcomes

# Example usage (topic provided at runtime):
# Should we use microservices architecture or monolithic architecture for our new e-commerce platform?
#
# Consider:
# - Team size and experience
# - Scaling requirements
# - Deployment complexity
# - Development velocity
# - Operational overhead
