# Documentation Generation Workflow
# Uses parallel pattern to generate different types of documentation independently

apiVersion: loom/v1
kind: Workflow
metadata:
  name: comprehensive-documentation
  description: Generate API docs, user guide, and examples in parallel
  labels:
    category: documentation
    complexity: medium

spec:
  type: parallel  # Changed from pattern: parallel
  merge_strategy: concatenate
  timeout_seconds: 600

  agent_ids:
    - api-documenter
    - technical-writer
    - example-creator

# Agent configs used (from ~/.loom/agents/):
# - api-documenter.yaml: API documentation specialist for creating comprehensive technical documentation
# - technical-writer.yaml: Technical writer for user-friendly guides and tutorials
# - example-creator.yaml: Example code specialist for practical, real-world code samples

# Example usage:
# "Generate documentation for our workflow orchestration system with 5 patterns:
# Debate, Fork-Join, Pipeline, Parallel, and Conditional. Include API reference,
# user guide, and example YAML files."
