# Security Analysis Workflow
# Uses parallel pattern for comprehensive multi-faceted security review

apiVersion: loom/v1
kind: Workflow
metadata:
  name: comprehensive-security-analysis
  description: Multi-stage security analysis with parallel SAST/DAST and threat modeling
  labels:
    category: security
    complexity: high

spec:
  type: parallel  # Changed from pattern: parallel
  merge_strategy: concatenate
  timeout_seconds: 1800

  tasks:
    - agent_id: sast-analyzer
      prompt: "Perform static application security testing (SAST) analysis"
    - agent_id: dast-analyzer
      prompt: "Perform dynamic application security testing (DAST) analysis"
    - agent_id: threat-modeler
      prompt: "Create threat model using STRIDE methodology"
    - agent_id: dependency-scanner
      prompt: "Scan dependencies for known vulnerabilities"
    - agent_id: compliance-auditor
      prompt: "Audit for security compliance (OWASP Top 10, GDPR)"

# Agent configs used (from $LOOM_DATA_DIR/agents/):
# - sast-analyzer.yaml: Static Application Security Testing specialist for code analysis
# - dast-analyzer.yaml: Dynamic Application Security Testing specialist for runtime analysis
# - threat-modeler.yaml: Threat modeling specialist using STRIDE methodology
# - dependency-scanner.yaml: Supply chain security specialist for vulnerability scanning
# - compliance-auditor.yaml: Security compliance auditor for regulatory frameworks

# Example usage:
# "Analyze our web application for security vulnerabilities:
#
# Code sample:
# func HandleLogin(w http.ResponseWriter, r *http.Request) {
#     username := r.FormValue(\"username\")
#     password := r.FormValue(\"password\")
#     query := \"SELECT * FROM users WHERE username='\" + username + \"' AND password='\" + password + \"'\"
#     rows, _ := db.Query(query)
# }
#
# System architecture:
# - Web-based user management
# - JWT authentication
# - PostgreSQL database
# - Deployed on AWS EC2
#
# Dependencies:
# - github.com/golang-jwt/jwt/v5 v5.0.0
# - github.com/lib/pq v1.10.9
#
# Check compliance with OWASP Top 10 and GDPR."
