apiVersion: loom/v1
kind: Workflow
metadata:
  name: vacation-planning-workflow
  version: "1.0.0"
  description: "Multi-agent workflow for comprehensive vacation planning with weather analysis"
  labels:
    domain: travel
    category: planning

spec:
  entrypoint: coordinator
  
  agents:
    - name: coordinator
      agent: vacation-coordinator
      description: "User-facing coordinator that manages the vacation planning process"

    - name: weather-analyst
      agent: weather-analyst
      description: "Provides weather analysis and forecasts for destinations"

    - name: vacation-planner
      agent: vacation-planner
      description: "Recommends destinations and creates detailed vacation plans"
    
  config:
    timeout_seconds: 1800
    max_workflow_turns: 200
    
  observability:
    export_traces: true
    export_metrics: true
    tags:
      workflow: vacation-planning
      version: "1.0.0"
